spring:
  datasource:
    url: jdbc:h2:file:./database/base
    driverClassName: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: 123qweQWE